CREATE TABLE kunde (
    kundennummer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR(50) NOT NULL,
    nachname VARCHAR(50) NOT NULL
);

CREATE TABLE bankkonto (
    kontonummer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kundennummer BIGINT NOT NULL,
    konto_pin VARCHAR(50) NOT NULL,
    kontostand DECIMAL(10,2) NOT NULL,

    CONSTRAINT fk_bankkonto_kunde FOREIGN KEY (kundennummer) REFERENCES kunde(kundennummer)
);

CREATE TABLE geldkarte (
    kartennummer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kontonummer BIGINT NOT NULL UNIQUE,
    karte_pin VARCHAR(4) NOT NULL,

    CONSTRAINT fk_geldkarte_konto FOREIGN KEY (kontonummer) REFERENCES bankkonto(kontonummer)
);

CREATE TABLE geldautomat (
    automatennummer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    bargeld DECIMAL(10,2) NOT NULL
);

CREATE TABLE transaktion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_kontonummer BIGINT,
    empfaenger_kontonummer BIGINT,
    geldautomat_nummer BIGINT,
    betrag DECIMAL(10, 2) NOT NULL,
    typ VARCHAR(50) NOT NULL,
    zeitpunkt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_trans_sender FOREIGN KEY (sender_kontonummer) REFERENCES bankkonto(kontonummer),
    CONSTRAINT fk_trans_empfaenger FOREIGN KEY (empfaenger_kontonummer) REFERENCES bankkonto(kontonummer),
    CONSTRAINT fk_trans_geldautomat FOREIGN KEY (geldautomat_nummer) REFERENCES geldautomat(automatennummer)
);